// Shown one at a time on the loading screen (src/app/(app)/loading.tsx).
// Source: "100 Ikigai Teachings and Sayings".
export const IKIGAI_SAYINGS: readonly string[] = [
  "Your ikigai lies at the intersection of what you love, what you're good at, what the world needs, and what you can be paid for.",
  "Life's purpose is not found in grand gestures, but in the small moments that bring joy.",
  "Even the smallest flower has a reason to bloom.",
  "Your ikigai is not something you find once and possess forever; it evolves as you do.",
  "The meaning of life is to find your gift; the purpose of life is to give it away.",
  "Every morning, ask yourself: \"What can I do today that aligns with my purpose?\"",
  "Your ikigai whispers to you in moments of deep satisfaction and flow.",
  "A life without purpose is like a ship without a compass.",
  "Your reason for being is written in the language of your heart.",
  "The best time to plant a tree was 20 years ago; the second best time is now.",
  "Start each day with gratitude for the gift of another sunrise.",
  "Find beauty in the ordinary, for that is where life truly resides.",
  "The way you do anything is the way you do everything.",
  "Small steps taken consistently lead to great journeys.",
  "Live as if every day matters, because it does.",
  "The present moment is the only moment where life happens.",
  "Wake up not because you have to, but because you want to.",
  "Let your daily rituals be acts of self-love and intention.",
  "Practice mono no aware—the bittersweet awareness of the impermanence of all things.",
  "Each breath is a new opportunity to begin again.",
  "A master is simply a student who never stopped learning.",
  "Growth happens in the space between comfort and challenge.",
  "Every expert was once a beginner who refused to give up.",
  "Wisdom comes not from avoiding mistakes, but from learning from them.",
  "The bamboo that bends survives the storm that breaks the oak.",
  "Kaizen—small improvements every day lead to remarkable transformations.",
  "Your potential is not fixed; it expands with every effort you make.",
  "The path to mastery is paved with patience and persistence.",
  "Learn from everyone, but follow your own inner compass.",
  "Embrace beginner's mind; there is always more to discover.",
  "We find ourselves through serving others.",
  "Your ikigai often lies in how you contribute to the lives of others.",
  "The bonds we create are the true treasures of life.",
  "Listen not just to respond, but to understand.",
  "Kindness is a language the deaf can hear and the blind can see.",
  "We rise by lifting others.",
  "Your presence is a present to the world.",
  "The heart that gives, gathers.",
  "Community is not just where you live, but how you live with others.",
  "Love is the bridge between two hearts and the foundation of ikigai.",
  "Work becomes art when you bring passion to it.",
  "Your profession should be a reflection of your values, not a betrayal of them.",
  "The craftsman's hands know what the mind has yet to understand.",
  "Excellence is not a skill, it's an attitude.",
  "When work aligns with purpose, Monday mornings become opportunities.",
  "The master craftsman sees each task as a chance to create something beautiful.",
  "Your work should feed your soul, not just your bank account.",
  "Take pride in the process, not just the outcome.",
  "The carpenter who loves wood creates more than furniture; he creates art.",
  "Let your work be your signature in the world.",
  "Life is like riding a bicycle—to keep your balance, you must keep moving.",
  "Balance is not something you find, it's something you create.",
  "The art of living well is finding harmony between effort and ease.",
  "Rest is not idleness, but preparation for the next phase of growth.",
  "Like the seasons, we too must learn when to grow and when to rest.",
  "Moderation in all things, including moderation.",
  "A life in balance feels light, even when carrying heavy responsibilities.",
  "The middle way leads to lasting contentment.",
  "Honor both your need for solitude and your need for connection.",
  "Balance is found not in perfection, but in the dance between extremes.",
  "Fall seven times, rise eight times. (Nana korobi ya oki)",
  "The strongest trees grow in the windiest places.",
  "Resilience is not about avoiding the storm, but learning to dance in the rain.",
  "Every setback is a setup for a comeback.",
  "The river that survives is the one that bends around the rocks.",
  "Strength grows in the moments when you think you can't go on but you keep going anyway.",
  "Your scars are proof that you are stronger than whatever tried to hurt you.",
  "The lotus flower blooms most beautifully from the deepest mud.",
  "Persistence is the hard work you do after you're tired of the hard work you already did.",
  "Courage is not the absence of fear, but action in spite of it.",
  "The answers you seek never come when the mind is restless.",
  "Know thyself, and you will know the universe.",
  "The longest journey you'll ever take is the journey within.",
  "Your intuition is your inner compass; trust its direction.",
  "Silence is not empty; it is full of answers.",
  "The wise person speaks less and listens more.",
  "Your authentic self is your greatest gift to the world.",
  "Inner peace begins the moment you choose not to allow others to control your emotions.",
  "The cave you fear to enter holds the treasure you seek.",
  "Wisdom is knowing that you know nothing; intelligence is knowing how to find out.",
  "Time is not money; time is life. Spend it wisely.",
  "The past is a memory, the future is a mystery, but life is lived in the present.",
  "Don't wait for tomorrow to live; tomorrow may never come.",
  "Presence is the greatest gift you can give to yourself and others.",
  "Life is not measured by the breaths you take, but by the moments that take your breath away.",
  "Each moment is a fresh beginning.",
  "The art of living is in the present moment, not in the past or future.",
  "Yesterday's mistakes cannot be changed, but today's choices can change tomorrow.",
  "Time spent in nature is never wasted time.",
  "The clock does not measure time; the heart does.",
  "We make a living by what we get, but we make a life by what we give.",
  "Your legacy is not what you leave behind, but what you build in others.",
  "The true measure of a life is not its duration, but its donation.",
  "Plant seeds of kindness wherever you go; you may never see the harvest, but others will.",
  "The best teachers are those who show you where to look, but don't tell you what to see.",
  "Leave this world a little better than you found it.",
  "Your life is your message to the world; make sure it's inspiring.",
  "The impact of a life well-lived ripples through generations.",
  "Immortality is achieved not through fame, but through the lives you touch.",
  "Your ikigai is complete when your life becomes a gift to others and yourself.",
]
