-- GENERATED by scripts/build-migration-sql.mjs (npm run db:build-sql) -- do not edit.
-- Migration status check -- READ-ONLY, changes nothing.
-- Covers the last 10 files in supabase/migrations/ (10 files, 135 schema objects).
--
-- Run in the Supabase SQL Editor of the project you want to inspect.
-- One row per migration file, in apply order:
--   applied      every table/column/function/policy/trigger/index it creates exists
--   PARTIAL      some exist -- inspect "missing" before re-running anything
--   NOT APPLIED  none exist
--   unverifiable the file only changes data, grants or existing definitions
--
-- Limits: it checks that objects exist by name, not that their definitions
-- match. A migration that only redefines an existing function or policy, or
-- only inserts/updates rows, shows as "unverifiable". Objects a later
-- migration drops or renames are checked under their final name.

with migrations(ord, migration) as (
  values
    (135, '20261011100001_ai_cost_report'),
    (136, '20261012100001_eval_operations_admin_only'),
    (137, '20261013100001_project_ember_readiness'),
    (138, '20261014100001_project_knowledge_gaps'),
    (139, '20261015100001_knowledge_gap_detection'),
    (140, '20261016100001_workstream_knowledge_in_project_search'),
    (141, '20261017100001_solution_requirements'),
    (142, '20261018100001_knowledge_gap_semantic_grouping'),
    (143, '20261019100001_solution_verification_records'),
    (144, '20261020100001_solution_baselines_and_decisions')
),
expected(migration, kind, schema_name, table_name, object_name) as (
  values
    ('20261011100001_ai_cost_report', 'column', 'public', 'ai_models', 'cached_input_cost_per_million'),
    ('20261011100001_ai_cost_report', 'view', 'public', null, 'ai_cost_daily'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_runs', 'eval_runs_insert_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_runs', 'eval_runs_update_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_results', 'eval_results_insert_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_results', 'eval_results_update_admin'),
    ('20261013100001_project_ember_readiness', 'function', 'public', null, 'project_measured_score'),
    ('20261013100001_project_ember_readiness', 'table', 'public', null, 'project_ember_readiness'),
    ('20261013100001_project_ember_readiness', 'index', 'public', null, 'project_ember_readiness_project_set_at_idx'),
    ('20261013100001_project_ember_readiness', 'function', 'public', null, 'project_ember_readiness_before_insert'),
    ('20261013100001_project_ember_readiness', 'trigger', 'public', 'project_ember_readiness', 'project_ember_readiness_before_insert'),
    ('20261013100001_project_ember_readiness', 'policy', 'public', 'project_ember_readiness', 'project_ember_readiness_select_member'),
    ('20261013100001_project_ember_readiness', 'policy', 'public', 'project_ember_readiness', 'project_ember_readiness_insert_curator'),
    ('20261014100001_project_knowledge_gaps', 'table', 'public', null, 'project_knowledge_gaps'),
    ('20261014100001_project_knowledge_gaps', 'index', 'public', null, 'project_knowledge_gaps_project_status_idx'),
    ('20261014100001_project_knowledge_gaps', 'index', 'public', null, 'project_knowledge_gaps_reported_by_idx'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_set_updated_at'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_knowledge_gaps_before_insert'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_before_insert'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_knowledge_gaps_before_update'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_before_update'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_select_reporter_or_curator'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_insert_member'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_update_curator'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_ember_readiness_signals'),
    ('20261015100001_knowledge_gap_detection', 'column', 'public', 'project_knowledge_gaps', 'occurrence_count'),
    ('20261015100001_knowledge_gap_detection', 'column', 'public', 'project_knowledge_gaps', 'last_occurred_at'),
    ('20261015100001_knowledge_gap_detection', 'table', 'public', null, 'project_knowledge_gap_occurrences'),
    ('20261015100001_knowledge_gap_detection', 'index', 'public', null, 'project_knowledge_gap_occurrences_gap_idx'),
    ('20261015100001_knowledge_gap_detection', 'index', 'public', null, 'project_knowledge_gap_occurrences_project_idx'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'project_knowledge_gap_occurrences_before_update'),
    ('20261015100001_knowledge_gap_detection', 'trigger', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_before_update'),
    ('20261015100001_knowledge_gap_detection', 'policy', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_select_own_or_curator'),
    ('20261015100001_knowledge_gap_detection', 'policy', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_update_own'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'knowledge_gap_similarity'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'withdraw_knowledge_gap_occurrence'),
    ('20261016100001_workstream_knowledge_in_project_search', 'function', 'public', null, 'knowledge_base_readable_via_project'),
    ('20261016100001_workstream_knowledge_in_project_search', 'policy', 'public', 'knowledge_sources', 'knowledge_sources_select_staff_or_owner_or_project_member'),
    ('20261016100001_workstream_knowledge_in_project_search', 'policy', 'public', 'documents', 'documents_select_staff_or_owner_or_project_member'),
    ('20261016100001_workstream_knowledge_in_project_search', 'policy', 'public', 'kb_vectors', 'kb_vectors_select_scoped'),
    ('20261017100001_solution_requirements', 'table', 'public', null, 'solution_requirements'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirements_project_idx'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_requirements', 'solution_requirements_set_updated_at'),
    ('20261017100001_solution_requirements', 'function', 'public', null, 'solution_requirements_before_update'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_requirements', 'solution_requirements_before_update'),
    ('20261017100001_solution_requirements', 'function', 'public', null, 'solution_requirement_is_draft'),
    ('20261017100001_solution_requirements', 'table', 'public', null, 'solution_requirement_sources'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirement_sources_requirement_idx'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirement_sources_knowledge_source_idx'),
    ('20261017100001_solution_requirements', 'table', 'public', null, 'solution_requirement_scope_links'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirement_scope_links_workstream_uniq'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirement_scope_links_object_uniq'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_requirement_scope_links_workstream_idx'),
    ('20261017100001_solution_requirements', 'table', 'public', null, 'solution_verification_methods'),
    ('20261017100001_solution_requirements', 'index', 'public', null, 'solution_verification_methods_requirement_idx'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_verification_methods', 'solution_verification_methods_set_updated_at'),
    ('20261017100001_solution_requirements', 'function', 'public', null, 'solution_requirement_child_before_write'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_requirement_sources', 'solution_requirement_sources_before_write'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_requirement_scope_links', 'solution_requirement_scope_links_before_write'),
    ('20261017100001_solution_requirements', 'trigger', 'public', 'solution_verification_methods', 'solution_verification_methods_before_write'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirements', 'solution_requirements_select_member'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirements', 'solution_requirements_insert_curator'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirements', 'solution_requirements_update_curator'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirements', 'solution_requirements_delete_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_sources', 'solution_requirement_sources_select_member'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_sources', 'solution_requirement_sources_insert_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_sources', 'solution_requirement_sources_update_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_sources', 'solution_requirement_sources_delete_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_scope_links', 'solution_requirement_scope_links_select_member'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_scope_links', 'solution_requirement_scope_links_insert_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_scope_links', 'solution_requirement_scope_links_update_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_requirement_scope_links', 'solution_requirement_scope_links_delete_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_verification_methods', 'solution_verification_methods_select_member'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_verification_methods', 'solution_verification_methods_insert_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_verification_methods', 'solution_verification_methods_update_curator_draft'),
    ('20261017100001_solution_requirements', 'policy', 'public', 'solution_verification_methods', 'solution_verification_methods_delete_curator_draft'),
    ('20261018100001_knowledge_gap_semantic_grouping', 'column', 'public', 'project_knowledge_gaps', 'embedding'),
    ('20261018100001_knowledge_gap_semantic_grouping', 'column', 'public', 'project_knowledge_gaps', 'embedding_model'),
    ('20261018100001_knowledge_gap_semantic_grouping', 'column', 'public', 'project_knowledge_gap_occurrences', 'embedding'),
    ('20261018100001_knowledge_gap_semantic_grouping', 'column', 'public', 'project_knowledge_gap_occurrences', 'embedding_model'),
    ('20261018100001_knowledge_gap_semantic_grouping', 'function', 'public', null, 'record_automatic_knowledge_gap'),
    ('20261019100001_solution_verification_records', 'table', 'public', null, 'solution_verification_records'),
    ('20261019100001_solution_verification_records', 'index', 'public', null, 'solution_verification_records_requirement_idx'),
    ('20261019100001_solution_verification_records', 'index', 'public', null, 'solution_verification_records_project_idx'),
    ('20261019100001_solution_verification_records', 'index', 'public', null, 'solution_verification_records_supersedes_uniq'),
    ('20261019100001_solution_verification_records', 'table', 'public', null, 'solution_verification_evidence'),
    ('20261019100001_solution_verification_records', 'index', 'public', null, 'solution_verification_evidence_record_idx'),
    ('20261019100001_solution_verification_records', 'index', 'public', null, 'solution_verification_evidence_artifact_idx'),
    ('20261019100001_solution_verification_records', 'function', 'public', null, 'solution_verification_records_before_update'),
    ('20261019100001_solution_verification_records', 'trigger', 'public', 'solution_verification_records', 'solution_verification_records_before_update'),
    ('20261019100001_solution_verification_records', 'function', 'public', null, 'record_solution_verification'),
    ('20261019100001_solution_verification_records', 'policy', 'public', 'solution_verification_records', 'solution_verification_records_select_member'),
    ('20261019100001_solution_verification_records', 'policy', 'public', 'solution_verification_evidence', 'solution_verification_evidence_select_member'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'holds_project_authority'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'project_self_approval_allowed'),
    ('20261020100001_solution_baselines_and_decisions', 'table', 'public', null, 'solution_evaluation_baselines'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_evaluation_baselines_project_idx'),
    ('20261020100001_solution_baselines_and_decisions', 'trigger', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_set_updated_at'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'solution_evaluation_baselines_before_update'),
    ('20261020100001_solution_baselines_and_decisions', 'trigger', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_before_update'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'solution_baseline_is_draft'),
    ('20261020100001_solution_baselines_and_decisions', 'table', 'public', null, 'solution_evaluation_baseline_items'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_evaluation_baseline_items_requirement_idx'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'solution_evaluation_baseline_items_before_write'),
    ('20261020100001_solution_baselines_and_decisions', 'trigger', 'public', 'solution_evaluation_baseline_items', 'solution_evaluation_baseline_items_before_write'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'activate_solution_baseline'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'new_solution_baseline_version'),
    ('20261020100001_solution_baselines_and_decisions', 'table', 'public', null, 'solution_waivers'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_waivers_baseline_idx'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_waivers_live_uniq'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'request_solution_waiver'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'decide_solution_waiver'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'withdraw_solution_waiver'),
    ('20261020100001_solution_baselines_and_decisions', 'table', 'public', null, 'solution_conformance_decisions'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_conformance_decisions_baseline_idx'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_conformance_decisions_pending_uniq'),
    ('20261020100001_solution_baselines_and_decisions', 'table', 'public', null, 'solution_conformance_decision_approvals'),
    ('20261020100001_solution_baselines_and_decisions', 'index', 'public', null, 'solution_conformance_decision_approvals_decision_idx'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'solution_baseline_snapshot'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'request_solution_conformance_decision'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'decide_solution_conformance_decision'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'withdraw_solution_conformance_decision'),
    ('20261020100001_solution_baselines_and_decisions', 'function', 'public', null, 'solution_decided_row_before_update'),
    ('20261020100001_solution_baselines_and_decisions', 'trigger', 'public', 'solution_waivers', 'solution_waivers_before_update'),
    ('20261020100001_solution_baselines_and_decisions', 'trigger', 'public', 'solution_conformance_decisions', 'solution_conformance_decisions_before_update'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_select_member'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_insert_curator'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_update_curator_draft'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baselines', 'solution_evaluation_baselines_delete_curator_draft'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baseline_items', 'solution_evaluation_baseline_items_select_member'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baseline_items', 'solution_evaluation_baseline_items_insert_curator_draft'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_evaluation_baseline_items', 'solution_evaluation_baseline_items_delete_curator_draft'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_waivers', 'solution_waivers_select_member'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_conformance_decisions', 'solution_conformance_decisions_select_member'),
    ('20261020100001_solution_baselines_and_decisions', 'policy', 'public', 'solution_conformance_decision_approvals', 'solution_conformance_decision_approvals_select_member')
),
checked as (
  select e.*,
    case e.kind
      when 'extension' then exists (select 1 from pg_extension x where x.extname = e.object_name)
      when 'table' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('r', 'p', 'v', 'm'))
      when 'view' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                               where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('v', 'm'))
      when 'column' then exists (select 1 from information_schema.columns ic
                                 where ic.table_schema = e.schema_name and ic.table_name = e.table_name and ic.column_name = e.object_name)
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                   where n.nspname = e.schema_name and p.proname = e.object_name)
      when 'policy' then exists (select 1 from pg_policies pp
                                 where pp.schemaname = e.schema_name and pp.tablename = e.table_name and pp.policyname = e.object_name)
      when 'trigger' then exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
                                  where not t.tgisinternal and n.nspname = e.schema_name and c.relname = e.table_name and t.tgname = e.object_name)
      when 'index' then exists (select 1 from pg_indexes i where i.schemaname = e.schema_name and i.indexname = e.object_name)
    end as present
  from expected e
)
select
  m.ord,
  m.migration,
  case
    when count(c.kind) = 0 then 'unverifiable'
    when bool_and(c.present) then 'applied'
    when bool_or(c.present) then 'PARTIAL'
    else 'NOT APPLIED'
  end as status,
  count(c.kind) filter (where c.present) as found,
  count(c.kind) as expected,
  string_agg(c.kind || ' ' || coalesce(c.table_name || '.', '') || c.object_name, ', ' order by c.kind, c.object_name)
    filter (where not c.present) as missing
from migrations m
left join checked c on c.migration = m.migration
group by m.ord, m.migration
order by m.ord;
