-- GENERATED by scripts/build-migration-sql.mjs (npm run db:build-sql) -- do not edit.
-- Migration status check -- READ-ONLY, changes nothing.
-- Covers the last 10 files in supabase/migrations/ (10 files, 57 schema objects).
--
-- Run in the Supabase SQL Editor of the project you want to inspect.
-- One row per migration file, in apply order:
--   applied      every table/column/function/policy/trigger/index it creates exists
--   PARTIAL      some exist -- inspect "missing" before re-running anything
--   NOT APPLIED  none exist
--   unverifiable the file only changes data, grants or existing definitions
--
-- Limits: it checks that objects exist by name, not that their definitions
-- match. A migration that only redefines an existing function or policy, or
-- only inserts/updates rows, shows as "unverifiable". Objects a later
-- migration drops or renames are checked under their final name.

with migrations(ord, migration) as (
  values
    (130, '20261006100001_ai_provider_self_hosted'),
    (131, '20261007100001_agency_scoped_builder_budgets'),
    (132, '20261008100001_live_handover_and_builder_share'),
    (133, '20261009100001_disable_self_registration'),
    (134, '20261010100001_ai_operation_logs_task'),
    (135, '20261011100001_ai_cost_report'),
    (136, '20261012100001_eval_operations_admin_only'),
    (137, '20261013100001_project_ember_readiness'),
    (138, '20261014100001_project_knowledge_gaps'),
    (139, '20261015100001_knowledge_gap_detection')
),
expected(migration, kind, schema_name, table_name, object_name) as (
  values
    ('20261006100001_ai_provider_self_hosted', 'column', 'public', 'ai_providers', 'is_self_hosted'),
    ('20261007100001_agency_scoped_builder_budgets', 'function', 'public', null, 'can_manage_builder_budget'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_ai_allowances', 'builder_ai_allowances_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_ai_allowances', 'builder_ai_allowances_manage_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_credit_grants', 'builder_credit_grants_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_credit_grants', 'builder_credit_grants_insert_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_llm_credentials', 'builder_llm_credentials_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_llm_credentials', 'builder_llm_credentials_manage_own_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'column', 'public', 'projects', 'builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'index', 'public', null, 'projects_builder_id_idx'),
    ('20261008100001_live_handover_and_builder_share', 'function', 'public', null, 'enforce_project_builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'trigger', 'public', 'projects', 'projects_enforce_builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'column', 'public', 'client_project_fees', 'builder_share_pct'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'client_project_fees', 'client_project_fees_select_builder_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'client_project_fees', 'client_project_fees_write_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'builder_progress_updates', 'builder_progress_updates_insert_owner_or_builder'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'builder_progress_updates', 'builder_progress_updates_update_owner_or_builder'),
    ('20261010100001_ai_operation_logs_task', 'column', 'public', 'ai_operation_logs', 'task'),
    ('20261010100001_ai_operation_logs_task', 'column', 'public', 'ai_operation_logs', 'cached_input_tokens'),
    ('20261010100001_ai_operation_logs_task', 'index', 'public', null, 'ai_operation_logs_task_created_at_idx'),
    ('20261011100001_ai_cost_report', 'column', 'public', 'ai_models', 'cached_input_cost_per_million'),
    ('20261011100001_ai_cost_report', 'view', 'public', null, 'ai_cost_daily'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_runs', 'eval_runs_insert_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_runs', 'eval_runs_update_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_results', 'eval_results_insert_admin'),
    ('20261012100001_eval_operations_admin_only', 'policy', 'public', 'eval_results', 'eval_results_update_admin'),
    ('20261013100001_project_ember_readiness', 'function', 'public', null, 'project_measured_score'),
    ('20261013100001_project_ember_readiness', 'table', 'public', null, 'project_ember_readiness'),
    ('20261013100001_project_ember_readiness', 'index', 'public', null, 'project_ember_readiness_project_set_at_idx'),
    ('20261013100001_project_ember_readiness', 'function', 'public', null, 'project_ember_readiness_before_insert'),
    ('20261013100001_project_ember_readiness', 'trigger', 'public', 'project_ember_readiness', 'project_ember_readiness_before_insert'),
    ('20261013100001_project_ember_readiness', 'policy', 'public', 'project_ember_readiness', 'project_ember_readiness_select_member'),
    ('20261013100001_project_ember_readiness', 'policy', 'public', 'project_ember_readiness', 'project_ember_readiness_insert_curator'),
    ('20261014100001_project_knowledge_gaps', 'table', 'public', null, 'project_knowledge_gaps'),
    ('20261014100001_project_knowledge_gaps', 'index', 'public', null, 'project_knowledge_gaps_project_status_idx'),
    ('20261014100001_project_knowledge_gaps', 'index', 'public', null, 'project_knowledge_gaps_reported_by_idx'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_set_updated_at'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_knowledge_gaps_before_insert'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_before_insert'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_knowledge_gaps_before_update'),
    ('20261014100001_project_knowledge_gaps', 'trigger', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_before_update'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_select_reporter_or_curator'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_insert_member'),
    ('20261014100001_project_knowledge_gaps', 'policy', 'public', 'project_knowledge_gaps', 'project_knowledge_gaps_update_curator'),
    ('20261014100001_project_knowledge_gaps', 'function', 'public', null, 'project_ember_readiness_signals'),
    ('20261015100001_knowledge_gap_detection', 'column', 'public', 'project_knowledge_gaps', 'occurrence_count'),
    ('20261015100001_knowledge_gap_detection', 'column', 'public', 'project_knowledge_gaps', 'last_occurred_at'),
    ('20261015100001_knowledge_gap_detection', 'table', 'public', null, 'project_knowledge_gap_occurrences'),
    ('20261015100001_knowledge_gap_detection', 'index', 'public', null, 'project_knowledge_gap_occurrences_gap_idx'),
    ('20261015100001_knowledge_gap_detection', 'index', 'public', null, 'project_knowledge_gap_occurrences_project_idx'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'project_knowledge_gap_occurrences_before_update'),
    ('20261015100001_knowledge_gap_detection', 'trigger', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_before_update'),
    ('20261015100001_knowledge_gap_detection', 'policy', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_select_own_or_curator'),
    ('20261015100001_knowledge_gap_detection', 'policy', 'public', 'project_knowledge_gap_occurrences', 'project_knowledge_gap_occurrences_update_own'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'knowledge_gap_similarity'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'record_automatic_knowledge_gap'),
    ('20261015100001_knowledge_gap_detection', 'function', 'public', null, 'withdraw_knowledge_gap_occurrence')
),
checked as (
  select e.*,
    case e.kind
      when 'extension' then exists (select 1 from pg_extension x where x.extname = e.object_name)
      when 'table' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('r', 'p', 'v', 'm'))
      when 'view' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                               where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('v', 'm'))
      when 'column' then exists (select 1 from information_schema.columns ic
                                 where ic.table_schema = e.schema_name and ic.table_name = e.table_name and ic.column_name = e.object_name)
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                   where n.nspname = e.schema_name and p.proname = e.object_name)
      when 'policy' then exists (select 1 from pg_policies pp
                                 where pp.schemaname = e.schema_name and pp.tablename = e.table_name and pp.policyname = e.object_name)
      when 'trigger' then exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
                                  where not t.tgisinternal and n.nspname = e.schema_name and c.relname = e.table_name and t.tgname = e.object_name)
      when 'index' then exists (select 1 from pg_indexes i where i.schemaname = e.schema_name and i.indexname = e.object_name)
    end as present
  from expected e
)
select
  m.ord,
  m.migration,
  case
    when count(c.kind) = 0 then 'unverifiable'
    when bool_and(c.present) then 'applied'
    when bool_or(c.present) then 'PARTIAL'
    else 'NOT APPLIED'
  end as status,
  count(c.kind) filter (where c.present) as found,
  count(c.kind) as expected,
  string_agg(c.kind || ' ' || coalesce(c.table_name || '.', '') || c.object_name, ', ' order by c.kind, c.object_name)
    filter (where not c.present) as missing
from migrations m
left join checked c on c.migration = m.migration
group by m.ord, m.migration
order by m.ord;
