-- GENERATED by scripts/build-migration-sql.mjs (npm run db:build-sql) -- do not edit.
-- Migration status check -- READ-ONLY, changes nothing.
-- Covers the last 10 files in supabase/migrations/ (10 files, 56 schema objects).
--
-- Run in the Supabase SQL Editor of the project you want to inspect.
-- One row per migration file, in apply order:
--   applied      every table/column/function/policy/trigger/index it creates exists
--   PARTIAL      some exist -- inspect "missing" before re-running anything
--   NOT APPLIED  none exist
--   unverifiable the file only changes data, grants or existing definitions
--
-- Limits: it checks that objects exist by name, not that their definitions
-- match. A migration that only redefines an existing function or policy, or
-- only inserts/updates rows, shows as "unverifiable". Objects a later
-- migration drops or renames are checked under their final name.

with migrations(ord, migration) as (
  values
    (126, '20261003100003_client_project_fees'),
    (127, '20261004100001_project_creation_approval'),
    (128, '20261004100002_project_live_status'),
    (129, '20261005100001_external_mcp_access'),
    (130, '20261006100001_ai_provider_self_hosted'),
    (131, '20261007100001_agency_scoped_builder_budgets'),
    (132, '20261008100001_live_handover_and_builder_share'),
    (133, '20261009100001_disable_self_registration'),
    (134, '20261010100001_ai_operation_logs_task'),
    (135, '20261011100001_ai_cost_report')
),
expected(migration, kind, schema_name, table_name, object_name) as (
  values
    ('20261003100003_client_project_fees', 'column', 'public', 'workstream_promotions', 'proposed_fee_amount'),
    ('20261003100003_client_project_fees', 'column', 'public', 'workstream_promotions', 'proposed_fee_currency'),
    ('20261003100003_client_project_fees', 'column', 'public', 'workstream_promotions', 'proposed_fee_period'),
    ('20261003100003_client_project_fees', 'table', 'public', null, 'client_project_fees'),
    ('20261003100003_client_project_fees', 'trigger', 'public', 'client_project_fees', 'client_project_fees_set_updated_at'),
    ('20261004100001_project_creation_approval', 'column', 'public', 'projects', 'approval_status'),
    ('20261004100001_project_creation_approval', 'column', 'public', 'projects', 'approval_decided_by'),
    ('20261004100001_project_creation_approval', 'column', 'public', 'projects', 'approval_decided_at'),
    ('20261004100001_project_creation_approval', 'column', 'public', 'projects', 'approval_decision_reason'),
    ('20261004100001_project_creation_approval', 'column', 'public', 'projects', 'pending_members'),
    ('20261004100001_project_creation_approval', 'index', 'public', null, 'projects_approval_status_pending_idx'),
    ('20261004100001_project_creation_approval', 'function', 'public', null, 'enforce_project_approval'),
    ('20261004100001_project_creation_approval', 'trigger', 'public', 'projects', 'projects_enforce_approval'),
    ('20261004100001_project_creation_approval', 'function', 'public', null, 'enforce_project_approval_membership'),
    ('20261004100001_project_creation_approval', 'trigger', 'public', 'project_members', 'project_members_enforce_approval'),
    ('20261005100001_external_mcp_access', 'table', 'public', null, 'mcp_access_users'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_access_users', 'mcp_access_users_select_self_or_admin'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_access_users', 'mcp_access_users_admin_insert'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_access_users', 'mcp_access_users_admin_delete'),
    ('20261005100001_external_mcp_access', 'table', 'public', null, 'mcp_approved_clients'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_approved_clients', 'mcp_approved_clients_select_authenticated'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_approved_clients', 'mcp_approved_clients_admin_insert'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_approved_clients', 'mcp_approved_clients_admin_update'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_approved_clients', 'mcp_approved_clients_admin_delete'),
    ('20261005100001_external_mcp_access', 'table', 'public', null, 'mcp_access_log'),
    ('20261005100001_external_mcp_access', 'index', 'public', null, 'mcp_access_log_user_created_idx'),
    ('20261005100001_external_mcp_access', 'index', 'public', null, 'mcp_access_log_created_idx'),
    ('20261005100001_external_mcp_access', 'policy', 'public', 'mcp_access_log', 'mcp_access_log_select_self_or_admin'),
    ('20261005100001_external_mcp_access', 'table', 'public', null, 'mcp_rate_counters'),
    ('20261005100001_external_mcp_access', 'function', 'public', null, 'mcp_rate_hit'),
    ('20261005100001_external_mcp_access', 'function', 'public', null, 'apply_oauth_read_only_policies'),
    ('20261005100001_external_mcp_access', 'policy', 'storage', 'objects', 'oauth_clients_no_insert'),
    ('20261005100001_external_mcp_access', 'policy', 'storage', 'objects', 'oauth_clients_no_update'),
    ('20261005100001_external_mcp_access', 'policy', 'storage', 'objects', 'oauth_clients_no_delete'),
    ('20261006100001_ai_provider_self_hosted', 'column', 'public', 'ai_providers', 'is_self_hosted'),
    ('20261007100001_agency_scoped_builder_budgets', 'function', 'public', null, 'can_manage_builder_budget'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_ai_allowances', 'builder_ai_allowances_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_ai_allowances', 'builder_ai_allowances_manage_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_credit_grants', 'builder_credit_grants_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_credit_grants', 'builder_credit_grants_insert_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_llm_credentials', 'builder_llm_credentials_select_own_agency_or_admin'),
    ('20261007100001_agency_scoped_builder_budgets', 'policy', 'public', 'builder_llm_credentials', 'builder_llm_credentials_manage_own_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'column', 'public', 'projects', 'builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'index', 'public', null, 'projects_builder_id_idx'),
    ('20261008100001_live_handover_and_builder_share', 'function', 'public', null, 'enforce_project_builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'trigger', 'public', 'projects', 'projects_enforce_builder_id'),
    ('20261008100001_live_handover_and_builder_share', 'column', 'public', 'client_project_fees', 'builder_share_pct'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'client_project_fees', 'client_project_fees_select_builder_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'client_project_fees', 'client_project_fees_write_agency_or_admin'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'builder_progress_updates', 'builder_progress_updates_insert_owner_or_builder'),
    ('20261008100001_live_handover_and_builder_share', 'policy', 'public', 'builder_progress_updates', 'builder_progress_updates_update_owner_or_builder'),
    ('20261010100001_ai_operation_logs_task', 'column', 'public', 'ai_operation_logs', 'task'),
    ('20261010100001_ai_operation_logs_task', 'column', 'public', 'ai_operation_logs', 'cached_input_tokens'),
    ('20261010100001_ai_operation_logs_task', 'index', 'public', null, 'ai_operation_logs_task_created_at_idx'),
    ('20261011100001_ai_cost_report', 'column', 'public', 'ai_models', 'cached_input_cost_per_million'),
    ('20261011100001_ai_cost_report', 'view', 'public', null, 'ai_cost_daily')
),
checked as (
  select e.*,
    case e.kind
      when 'extension' then exists (select 1 from pg_extension x where x.extname = e.object_name)
      when 'table' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                                where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('r', 'p', 'v', 'm'))
      when 'view' then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                               where n.nspname = e.schema_name and c.relname = e.object_name and c.relkind in ('v', 'm'))
      when 'column' then exists (select 1 from information_schema.columns ic
                                 where ic.table_schema = e.schema_name and ic.table_name = e.table_name and ic.column_name = e.object_name)
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                                   where n.nspname = e.schema_name and p.proname = e.object_name)
      when 'policy' then exists (select 1 from pg_policies pp
                                 where pp.schemaname = e.schema_name and pp.tablename = e.table_name and pp.policyname = e.object_name)
      when 'trigger' then exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
                                  where not t.tgisinternal and n.nspname = e.schema_name and c.relname = e.table_name and t.tgname = e.object_name)
      when 'index' then exists (select 1 from pg_indexes i where i.schemaname = e.schema_name and i.indexname = e.object_name)
    end as present
  from expected e
)
select
  m.ord,
  m.migration,
  case
    when count(c.kind) = 0 then 'unverifiable'
    when bool_and(c.present) then 'applied'
    when bool_or(c.present) then 'PARTIAL'
    else 'NOT APPLIED'
  end as status,
  count(c.kind) filter (where c.present) as found,
  count(c.kind) as expected,
  string_agg(c.kind || ' ' || coalesce(c.table_name || '.', '') || c.object_name, ', ' order by c.kind, c.object_name)
    filter (where not c.present) as missing
from migrations m
left join checked c on c.migration = m.migration
group by m.ord, m.migration
order by m.ord;
